rustwasm/gloo

Cargo.toml
crates/router/Cargo.toml
crates/router/src/lib.rs
crates/timers/Cargo.toml

Uses generics  as endpoints: requires a function to update app state, and one to update a wasm_bindgen Closure.

Added router crate

---

CONTRIBUTING.md

Adding in note about how to handle Futures / Streams

---

crates/timers/src/lib.rs

Fixes #39 
(#38 should be merged first, and then I'll resolve conflicts)

timers: use Closure::once for timeouts

---

crates/timers/src/callback.rs
crates/timers/src/future.rs
crates/timers/src/lib.rs
crates/timers/src/sys.rs

@fitzgen / @OddCoincidence 
`gloo-timers` doesn't work in web workers at all right now, because `web_sys::window()` wants to cast the global namespace into a `Window` object, which doesn't exist in worker contexts. So I just dropped us back down to raw `#[wasm_bindgen]` methods.
This might be something better fixed in wasm-bindgen later though. There does exist this thing: [WindowOrWorkerGlobalScope](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope) which is a nice view over what global methods are available in both Window and Worker contexts. However as stated in that documentation:
> Note: WindowOrWorkerGlobalScope is a mixin and not an interface; you can't actually create an object of type WindowOrWorkerGlobalScope.
So I guess this thing is probably not …

Fix timers in web workers

---

crates/timers/src/callback.rs
crates/timers/tests/web.rs

Otherwise Interval only works on first callback and fails after that

gloo-timers: don't consume callback in Interval closure

---

CONTRIBUTING.md

See https://github.com/rustwasm/gloo/issues/50#issuecomment-481363615 for more context.

Improving the RFC process

---

rfcs/001-mid-level-file-api.md

[rendered](https://github.com/rustwasm/gloo/blob/ec9c0c376ead79ff690d124c7b59789650dd4ea8/rfcs/001-mid-level-file-api.md)
As we've settled on an RFC process, I'd like to continue #50 here.

Add a mid-level file-rfc

---

CONTRIBUTING.md

cc @Pauan @thedodd @alexcrichton 
Fixes #66

Add docs on versioning and publishing releases to CONTRIBUTING.md

---

crates/console-timer/Cargo.toml
crates/events/Cargo.toml
crates/events/src/lib.rs
crates/timers/Cargo.toml
crates/timers/src/callback.rs
crates/timers/src/future.rs

Not sure this is an improvement, but hey, at least it fixes a TODO.
I also sneaked in a `Cargo.toml` change to avoid a warning.

Derive Debug impls

---

crates/events/src/lib.rs
crates/events/tests/web.rs

`wasm-bindgen` previously did not support closures with arguments by reference, but now it has some initial support. Let's use it!

gloo_event: Take events by reference

---

README.md

This was the best thing I could come up with for small and interesting and generally showing off things we have support for today.
Fixes #80

Add an example to the README

---

examples/clock/README.md

This is mostly useful because of the usage of '--target no-modules' as a wasm-pack option.

Add a readme to the clock example

---

crates/timers/Cargo.toml
crates/timers/src/callback.rs

This has been fixed before in a different way by #56.
But was removed again by #103 to solve #96.
I think the solution offered in this PR should solve #96 without breaking the fix provided by #103.
Related: https://github.com/rustwasm/wasm-bindgen/issues/1046.

Fix timers to work in workers too.

---

.gitignore
Cargo.toml
crates/events/tests/web.rs
crates/file/Cargo.toml
crates/file/src/blob.rs
crates/file/src/file_list.rs
crates/file/src/file_reader.rs
crates/file/src/lib.rs
crates/file/tests/web.rs
crates/timers/src/future.rs
crates/timers/tests/web.rs
src/lib.rs

This carries on from the work in #83 from @rylev. I've tried to address the issues in that thread.
Closes #47

Files implementation

---

Cargo.toml
crates/file/README.md
crates/file/tests/web.rs
crates/storage/Cargo.toml
crates/storage/README.md
crates/storage/src/errors.rs
crates/storage/src/lib.rs
crates/storage/src/local_storage.rs
crates/storage/src/session_storage.rs
crates/storage/tests/local_storage.rs
crates/storage/tests/session_storage.rs
src/lib.rs

Add wrappers for web storage API

---

crates/file/Cargo.toml
crates/file/README.md
crates/file/src/lib.rs
crates/timers/Cargo.toml

Make docs.rs builds include the futures feature.

Make docs.rs include futures functionality

---

crates/file/src/blob.rs

Use `Uint8Array::view` instead of `Uint8Array::from` to avoid making two copies of slices passed to `Blob::new`.
Fixes #150

Remove the unnecessary copy in `Blob::new`

---

crates/console/src/macros.rs

Noticed the discussion on discord and thought I'd contribute a fix.
Gets rid of a repetition that is not allowed according to [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/console/dir), which only mentions one single argument. Adds two examples that get picked up by doctesting to verify the fix.

Fix dir, dirxml macros in gloo-console

---

crates/console/src/console_dbg.rs

```rust
let a = 1;
gloo_console::console_dbg!("123", a, a + 1);
gloo_console::console_dbg!(String::from("123"));
gloo_console::console!(b());
let b: JsString = "123".into();
gloo_console::console!(b);
gloo_console::console!({let c: JsString = "cc".into(); c});
```

Fixes `console_dbg!` and `console!` expression output. Bold src info.

---

crates/console/src/lib.rs
crates/file/src/file_reader.rs
crates/history/Cargo.toml
crates/history/src/any.rs
crates/history/src/browser.rs
crates/history/src/error.rs
crates/history/src/hash.rs
crates/history/src/history.rs
crates/history/src/lib.rs
crates/history/src/location.rs
crates/history/src/state.rs
crates/history/src/utils.rs
crates/history/tests/browser_history.rs
crates/history/tests/browser_history_feat_serialize.rs
crates/history/tests/hash_history.rs
crates/history/tests/hash_history_feat_serialize.rs
crates/render/src/lib.rs
crates/timers/src/future.rs

This pull request consists of the following changes:
- `HashHistory` for hash-based history access.
- `Location` is now a struct and its content will be stable after created by `History::location()`.
- `Location` now have an `id` that is unique to itself.
- States now uses downcasting in all occasions.

Hash-based History type & Unified Location.

---

crates/history/src/any.rs
crates/history/src/browser.rs
crates/history/src/hash.rs
crates/history/src/history.rs
crates/history/src/lib.rs
crates/history/src/memory.rs
crates/history/src/utils.rs
crates/history/tests/memory_history.rs
crates/history/tests/memory_history_feat_serialize.rs

This pull request adds memory-based history.
Fix #166.

Memory-based History

---

Cargo.toml
crates/worker/Cargo.toml
crates/worker/src/lib.rs
crates/worker/src/link.rs
crates/worker/src/pool.rs
crates/worker/src/worker/mod.rs
crates/worker/src/worker/private.rs
crates/worker/src/worker/public.rs
crates/worker/src/worker/queue.rs
src/lib.rs

Migrate `yew-agent` to `gloo-worker`
The code in this PR is moved from the [Yew repository](https://github.com/yewstack/yew) as of commit yewstack/yew@6f6519d. All the credits go to original code authors.

Add `gloo-worker` crate

---

crates/timers/src/callback.rs

Add support for node.js in `gloo-timers`. The motivation is to enable [rust-libp2p](https://github.com/libp2p/rust-libp2p/)'s usage in node.js.
This adds an enum variant to the `WindowOrWorker` struct. An alternative would be to remove that enum entirely and bind to the global `setTimeout`, `setInterval`, `clearTimeout` and `clearInterval` functions directly. From my understanding, they should be available in window, web workers and node.js (as well as deno). For now, I've stuck to the enum variant. Let me know what you prefer.
The node.js detection logic is akin to [how the `browser-or-node` npm package](https://github.com/flexdinesh/browser-or-node/blob/ae67a84b7cdc65021a198b18f16c3bdbf4b480d8/src/index.js#L4-L7) does it. What might also be possible is to assume node.js if no window or …

Add node.js support for timers

---

crates/timers/Cargo.toml

Remove the now unused `web-sys` dependency from the `gloo-timers` crate. This should've been part of #185 but was forgotten.
@hamza1311

Remove `web-sys` dependency in `gloo-timers`

---

crates/file/src/blob.rs
crates/file/src/file_list.rs

Impl Clone and PartialEq for File and Blog

---

crates/net/src/http/mod.rs
crates/net/tests/http.rs

In draft until feedback on approach is given in issue #199 thread

add `json()` impl to `Request`

---

crates/events/README.md

Using the absolute link to the docs, so that it works anywhere.

[events] Fix link to `EventListener` doc in README

---

crates/net/src/http/headers.rs
crates/utils/Cargo.toml
crates/utils/src/iter.rs
crates/utils/src/lib.rs

This PR moves `UncheckedIter` from `gloo_net::http::headers` to `gloo_utils::iter`.

Move UncheckedIter to gloo-utils

---

crates/utils/src/errors.rs

Implement `std::error::Error` for `gloo_utils::errors::JsError`.
Closes #216.

Implement std Error trait for JsError

---

crates/net/src/websocket/futures.rs

Currently, WebSockets can only be created without specifying the protocol. I've added support for either specifying a single protocol using `WebSocket::open_with_protocol` or a list of protocols with `WebSocket::open_with_protocols`

Added support for specifying Websocket Protocols

---

crates/file/Cargo.toml
crates/file/src/blob.rs
crates/file/src/lib.rs
crates/file/src/object_url.rs
crates/file/tests/web.rs

The [`createObjectUrl`](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL) API is offered by the browser to create URLs from Blobs that are too large to represent as data urls. The resulting url is along the lines of `blob:[origin]://[uuid]`. There's a counter part [`revokeObjectURL`](https://developer.mozilla.org/en-US/docs/Web/API/URL/revokeObjectURL) that releases the URL again. Rust lends itself to an abstraction that automatically revokes the url when it is not need any longer.
A `struct ObjectUrl` abstracts the allocation of a specific ObjectUrl. It uses reference counting to revoke the Url after the last user drops its use. It can be created from a `Blob`, `File` or directly from a `web_sys::Blob`. A `Deref` implemention allows access to the stringly-typed url …

[rfc] Implement an ObjectUrl wrapper

---

website/docusaurus.config.js

Instead of opening gloo's doc.rs page allow the user to select a crate for documentation

Add dropdown for doc.rs in website

---

crates/console/Cargo.toml
crates/console/src/lib.rs
crates/net/Cargo.toml
crates/net/src/http/mod.rs
crates/net/src/websocket/futures.rs
crates/storage/Cargo.toml

There is [an issue](https://github.com/tkaitchuck/aHash/issues/95) with cyclic dependency when `serde-serialize` feature is enabled in `wasm-bindgen`. Current suggestion is to use `js_sys` instead to avoid it.
I’ve checked and modified every crate that was enabling this feature:
- `console` was easy to change
- `storage` didn’t actually depend on this feature, so I just removed it.
- `net` this one was a bit tricky and this the create that I couldn’t run tests for.
I ran non-wasm tests, and wasm tests for console and storage.

fix: Break dependency cycle by not using serde-serialize

---

.github/workflows/tests.yml
examples/markdown/src/bin/example_markdown_test_server.rs

This pull request fixes an issue where: 
- gloo-worker tests will fail if test server does not start up before tests are run.
- wasm-bindgen now requires CORP headers.

Fix gloo-worker tests

---

.github/workflows/tests.yml
crates/file/src/blob.rs
crates/file/src/file_list.rs
crates/history/tests/browser_history.rs
crates/history/tests/browser_history_feat_serialize.rs
crates/history/tests/hash_history.rs
crates/history/tests/hash_history_feat_serialize.rs
crates/history/tests/utils.rs
examples/markdown/src/bin/example_markdown_test_server.rs

This pull request addresses random test failures of `gloo-history` by implementing an automatic retry strategy that usually presents in modern browser testing framework (cypress / playwright).

Fix history tests

---

.github/workflows/tests.yml
crates/net/Cargo.toml
crates/net/README.md
crates/net/src/error.rs
crates/net/src/eventsource/futures.rs
crates/net/src/eventsource/mod.rs
crates/net/src/lib.rs
crates/net/src/websocket/futures.rs

Inspired by the WebSocket API.
Example usage:
```rust
use gloo_net::eventsource::futures::EventSource;
use wasm_bindgen_futures::spawn_local;
use futures::{stream, StreamExt};
let mut es = EventSource::new("http://api.example.com/ssedemo.php").unwrap();
let stream_1 = es.subscribe("some-event-type").unwrap();
let stream_2 = es.subscribe("another-event-type").unwrap();
spawn_local(async move {
let mut all_streams = stream::select(stream_1, stream_2);
while let Some(Ok((event_type, msg))) = all_streams.next().await {
console_log!(format!("1. {}: {:?}", event_type, msg))
}
console_log!("EventSource Closed");
})
```
TODO:
Fixes https://github.com/hamza1311/reqwasm/issues/8
Fixes https://github.com/rustwasm/gloo/issues/8

Provides an EventSource implementation

---

crates/net/src/websocket/mod.rs

Adds an `std::error::Error` implementation for `gloo_net::websocket::WebSocketError`.

Add std::error::Error impl for WebSocketError

---

crates/timers/src/callback.rs

Closes #254 by improving verbage

gloo_timers, ambiguous verbage

---

crates/net/Cargo.toml
crates/net/src/error.rs
crates/net/src/http/mod.rs

I'm trying to use `gloo-net` in a web extension with manifest V3 but this does not work because of #201.
Fortunately @cdata [found a workaround](https://github.com/cdata/gloo/commit/b23035decc9ce41f40680d52ac7b85add0d00104) :smiley:
That at least avoids a panic but my service worker of the web extension does not have the `DedicadedWorkerGlobalScope` so I changed it to `WorkerGlobalScope` because as far as I know a `DedicadedWorkerGlobalScope` is a specialization of `WorkerGlobalScope`.
What do you think?

Gloo net fetch in worker

---

crates/net/Cargo.toml

* remove the deprecated `wasm-bindgen/serde-serialize`
* mark `gloo-utils/serde` optional under `json`
* enable `serde/derive` only for testing

fix: cyclic dependency for gloo-net websocket feature

---

crates/net/Cargo.toml
crates/net/src/websocket/futures.rs

I notice the following error:
And it's 100% reproduced when `wasm-pack test --chrome`.
It's a racing condition: 
* call `Websocket::close`, which **consumes the ownership**.
* `Websocket::drop` is executed emmediately
* call `self.ws.close()` the second time (and it doesn't matter).
* the closures (event listeners) are dropped (and it matters).
* `self.ws.onclose` is called with destroyed `close` callback.
Solution:
* bind`open/close` event listeners once (which I think okay, tell me if not)
* unbind the `open/message/error` eventlisteners when dropping
* trigger `close` event to notify the user (and unbind).

fix(ws): calling close event with destroyed close callback

---

crates/utils/src/format/json.rs

examples in the documentations were swapped between `into_serde` and `from_serde`

docs: correct format examples Fixes #276

---

crates/net/src/websocket/futures.rs

I have just found out that the following code hangs if no server is running on port 9321:
```rust
let ws = WebSocket::open("ws://localhost:9321").unwrap();
let (mut sender, mut receiver) = ws.split();
let _ = sender.send(Message::Text("test".into())).await;
```
this is because if the server is not running the `open_callback` is not called and the `waker` is not waked causing `poll_ready` to always return `Pending`. 
This PR adds a `wake()` call on the `error_callback` so that `poll_ready` will move to `Ready` also if an error occurs.

Prevent Websocket send from hanging if connection fails.

---

crates/file/tests/web.rs
crates/history/src/hash.rs
crates/net/Cargo.toml
crates/net/src/eventsource/futures.rs
crates/net/src/websocket/futures.rs
crates/net/tests/http.rs

This pull request fixes clippy.

Fix Clippy

---

.github/workflows/tests.yml
CONTRIBUTING.md
crates/timers/src/callback.rs
crates/timers/tests/node.rs

~~It's a regression from #96 introduced by #185, and I have no idea why calling `clearTimeout` is failed in browser, but my patch definitely resolves the error.~~
It's a side effect introduced by bundler, and we workaround it. more details in https://github.com/rustwasm/gloo/pull/283#issuecomment-1396668213

fix: `clearTimeout` illegal invocation with bundler (#187)

---

crates/history/src/browser.rs
crates/history/tests/browser_history.rs

To prevent situations of 'already mutably borrowed: BorrowError' when invoking callbacks from BrowserHistory where state is in use, drop the borrow before invoking the callbacks.
This fixes #284

(history): Drop states borrow before callback invocation

---

.github/workflows/lint-fmt.yml
.github/workflows/tests.yml

Basically all of the `actions-rs/*` actions are unmaintained. See <https://github.com/actions-rs/toolchain/issues/216> for more information. Due to their age they generate several warnings in CI runs, for example in https://github.com/rustwasm/gloo/actions/runs/4136537026:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions-rs/toolchain@v1, actions-rs/cargo@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
To get rid of some of those warnings the occurrences of `actions-rs/cargo` are replaced by direct invocations of `cargo`.

Replace unmaintained actions-rs/cargo actions in CI workflows

---

.github/workflows/lint-fmt.yml
.github/workflows/tests.yml

Basically all of the `actions-rs/*` actions are unmaintained. See <https://github.com/actions-rs/toolchain/issues/216> for more information. Due to their age they generate several warnings in CI runs, for example in https://github.com/rustwasm/gloo/actions/runs/4136537026:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions-rs/toolchain@v1, actions-rs/cargo@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
To get rid of some of those warnings the occurrences of `actions-rs/toolchain` are replaced by [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain).

Replace unmaintained actions-rs/toolchain action in CI workflows

---

Cargo.toml
src/lib.rs

This turns the individual subcrates into optional features. By default, all features are enabled, to ensure this change is not a breaking change. But if needed, default features can be turned off and only the modules needed enabled.

Modularizes gloo

---

crates/worker/src/lib.rs

Fixes a broken link in library help text.

Fix typo in gloo-worker help

---

Cargo.toml
src/lib.rs

[gloo documentation](https://docs.rs/gloo/0.8.0/gloo/index.html) currently does not show you the documentation of the subcrates. Also searching does not work in the supercrate.
This can be solved by adding `#[doc(inline)]` on every crate reexport.

doc: Inline documentation in the supercrate

---

crates/net/Cargo.toml
crates/net/src/eventsource/mod.rs

The aim is to make it a little easier to debug and write more robust logic when handling an eventsource connection.

Add `PartialEq, Eq, PartialOrd, Ord, Hash` for eventsource `State`

---

crates/history/Cargo.toml
crates/history/src/any.rs
crates/history/src/browser.rs
crates/history/src/hash.rs
crates/history/src/history.rs
crates/history/src/memory.rs
crates/history/tests/browser_history_feat_serialize.rs
crates/history/tests/hash_history_feat_serialize.rs
crates/history/tests/memory_history_feat_serialize.rs

The state module uses Serialize and Deserialize as derive macros, but those are only available with the derive feature.
Also simplify some cfg expressions in the same crate.

history: Fix required feature set of serde dependency

---

crates/history/src/browser.rs
crates/history/src/hash.rs

history: Use thread_local!'s lazy initialization instead of RefCell<Option<_>>

---

crates/net/src/http/mod.rs

Docs are not currently generated for `RequestBuilder` or `ResponseBuilder`:
These types need to be made public here to fix this
fixes #353

Make RequestBuilder and ResponseBuilder public for docs

---

.github/workflows/tests.yml
CHANGELOG.md
Cargo.toml
crates/console/Cargo.toml
crates/dialogs/Cargo.toml
crates/events/Cargo.toml
crates/events/src/lib.rs
crates/file/Cargo.toml
crates/history/Cargo.toml
crates/net/Cargo.toml
crates/render/Cargo.toml
crates/storage/Cargo.toml
crates/timers/Cargo.toml
crates/utils/Cargo.toml
crates/worker-macros/Cargo.toml
crates/worker/Cargo.toml
examples/clock/Cargo.toml
examples/markdown/Cargo.toml
examples/prime/Cargo.toml

This pull request migrates to edition 2021.
Since wasm-bindgen requires 1.56, there is no benefit to keep crates at edition 2018.
Upgrading the crates to edition 2021 will enable the rust-version field which suppresses clippy for lints not available in MSRV.
I have calculated the MSRV with `cargo-msrv`, which is 1.64.

Migrate to Edition 2021

---

CHANGELOG.md
crates/events/src/lib.rs

I needed to compare the options of an event listener, I don't think it hurts adding support for `PartialEq` and `Eq` for the relevant types.

Add traits PartialEq and Eq to EventListenerOptions, and EventListenerPhase

---

CHANGELOG.md
crates/history/src/any.rs
crates/history/src/browser.rs
crates/history/src/error.rs
crates/history/src/hash.rs
crates/history/src/history.rs
crates/history/src/lib.rs
crates/history/src/location.rs
crates/history/src/memory.rs
crates/history/src/query.rs
crates/history/tests/query.rs

Introduces the `FromQuery` and `IntoQuery` traits to allow for customizing how query strings are encoded and decoded. Introduces the
- This PR is related to issue #362.
- I have taken care to make sure that this PR does not break any consumers of this crate. 
Because this PR introduces quite a few new things, allow me to walk through it an explain what is happening here.
The `History` trait has some methods that allow specifying a query parameter. This query parameter must implement `Serialize`. It is encoded using `serde_urlencoded`. These return a `HistoryResult<()>`, which expands to a `Result<(), HistoryError>`.
```rust
impl History {
fn push_with_query<'a, Q>(&self, route: impl Into<Cow<'a, str>>, query: Q) -> HistoryResult<()>
where Q: Serialize;
fn replace_with_query<'a, Q>(&self, …
```

Introduces the FromQuery and IntoQuery traits.

---

crates/net/src/websocket/futures.rs

On server side, websocket may create from WebSocketPair. So we need `TryFrom<web_sys::WebSocket>`.
https://docs.rs/worker/latest/src/worker/websocket.rs.html#26-31

Add `TryFrom<web_sys::WebSocket>`

---

CHANGELOG.md
crates/net/Cargo.toml
crates/net/src/websocket/futures.rs
crates/net/src/websocket/io_util.rs
crates/net/src/websocket/mod.rs

Implements `AsyncWrite` and `AsyncRead` on `WebSocket` behind the `io-util` feature flag.
This code was originally living in an ad hoc fashion, in our [IronRDP repository](https://github.com/Devolutions/IronRDP/blob/3d98cd1d9476e1fae84f21771df2ef7f4cd189f7/crates/ironrdp-web/src/websocket.rs), and I thought it was best to upstream it. In addition to the unit tests, I can confirm it works when running long-lived RDP sessions in the browser.
Closes https://github.com/rustwasm/gloo/issues/25

feat(net): AsyncWrite and AsyncRead for WebSocket

---

Cargo.lock
crates/worker/src/actor/bridge.rs

Fix #387.
This pull request removes cloning of bridges.
This is a breaking change.
If users want to share worker bridges, they can use `Rc`.

Remove Cloning on WorkerBridge

---

Cargo.lock
crates/history/Cargo.toml
crates/history/src/utils.rs

This should fix https://github.com/rustwasm/gloo/issues/369 most of the time.
Without any changes the Cargo.lock changed after building, that's in the first commit (I can squish it into one).
Using window.performance.now() is not an option because it starts the time when the website loads and thats why I've added js-sys as a dependency.
Everything else should be documented in the code.
Instead of OnceLock it's also possible to use the unprotected AtomicU32 as before and a Once to initialize it.
Edit: the option with Once is available with 1.64 - which I didn't realize that it has/should be compatible with.

History id start

---

crates/net/src/eventsource/futures.rs
crates/net/src/websocket/futures.rs
crates/net/src/websocket/io_util.rs

The assertions were not doing anthing before, they were only queued to
run
Proof that they are running now: #393
Fixes: #368

Execute websocket test assertions

---

Cargo.lock

Update Cargo.lock (2)

---

crates/history/Cargo.toml
crates/history/src/any.rs
crates/history/src/lib.rs
crates/history/src/state.rs

cc https://github.com/rustwasm/gloo/pull/411#discussion_r1421370667 https://github.com/rustwasm/gloo/pull/424#issuecomment-1848357604
@futursolo @hamza1311

Remove the flags what to expect WASI targets.

---

Cargo.lock
crates/net/Cargo.toml
crates/net/src/http/request.rs

This avoids the need to detect whether the module is running in the main browser thread or in a WebWorker.
This matches how `setInterval` and related functions are handled by the gloo-timers crate.
See https://github.com/rustwasm/wasm-bindgen/discussions/3863

Use direct global binding for `fetch` in place of web_sys fetch bindings

---

.github/workflows/tests.yml
Cargo.lock
crates/net/Cargo.toml
crates/net/tests/http.rs
crates/net/tests/query.rs

Tests to reproduce #484 
Fixed by ~~#485~~ #474

Add `wasm-pack` tests for `net` to CI

---

crates/worker/src/actor/traits.rs

[WorkerSpawner](https://docs.rs/gloo-worker/latest/gloo_worker/struct.WorkerSpawner.html) is at `crate::WorkerSpawner`, not `crate::spawner::WorkerSpawner`
Fixes #449

Fix broken docs link
